name: Update submodules

on:
  push:
    branches: [main]

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update submodules
        run: |
          git submodule update --init --recursive
